import { assert, test } from 'vitest'
import * as styles from '../src/content-zoom'

function testZoomBodyStylesSkipNonNumericValues() {
  assert.strictEqual(
    typeof styles.createZoomBodyStyles,
    'function',
    'Expected zoom body styles to be built by a testable helper',
  )

  const result = styles.createZoomBodyStyles(
    {
      width: '',
      height: 'auto',
      columnWidth: '640px',
      columnGap: '32px',
      paddingTop: 'not-a-number',
      paddingBottom: '20px',
      paddingLeft: undefined,
      paddingRight: '0px',
    },
    2,
  )

  assert.deepStrictEqual(result, {
    transformOrigin: 'top left',
    transform: 'scale(2)',
    columnWidth: '320px',
    columnGap: '16px',
    paddingBottom: '10px',
    paddingRight: '0px',
  })
  assert.ok(
    !Object.values(result).some((value) => String(value).includes('NaN')),
    'zoom styles must never emit NaNpx',
  )
}

function testZoomBodyStylesCanUseCurrentLayout() {
  assert.strictEqual(
    typeof styles.createZoomLayoutBodyStyleSource,
    'function',
    'Expected zoom body styles to be buildable from the current layout',
  )

  const source = styles.createZoomLayoutBodyStyleSource(
    {
      name: 'reflowable',
      width: 1000,
      height: 800,
      columnWidth: 460,
      gap: 40,
    },
    'horizontal',
  )
  const result = styles.createZoomBodyStyles(source, 2)

  assert.deepStrictEqual(result, {
    transformOrigin: 'top left',
    transform: 'scale(2)',
    width: '500px',
    height: '400px',
    columnWidth: '230px',
    columnGap: '20px',
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '10px',
  })
}

function testZoomBodyStylesUseVerticalPhysicalAxes() {
  const source = styles.createZoomLayoutBodyStyleSource(
    {
      name: 'reflowable',
      width: 1000,
      height: 800,
      columnWidth: 460,
      gap: 40,
    },
    'horizontal',
    'vertical-rl',
  )
  const result = styles.createZoomBodyStyles(source, 2, 'vertical-rl')

  assert.deepStrictEqual(result, {
    transformOrigin: 'top right',
    transform: 'scale(2)',
    width: '500px',
    height: '400px',
    columnWidth: '390px',
    columnHeight: '230px',
    columnGap: '0px',
    rowGap: '20px',
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '10px',
  })
}

function testZoomBodyStylesUseSinglePageVerticalStride() {
  const source = styles.createZoomLayoutBodyStyleSource(
    {
      name: 'reflowable',
      width: 1000,
      height: 800,
      columnWidth: 1000,
      gap: 40,
    },
    'horizontal',
    'vertical-rl',
  )

  assert.strictEqual(source.columnHeight, '960px')
  assert.strictEqual(source.rowGap, '40px')
}

function testZoomMediaUsesScaledContentColumnWidth() {
  assert.strictEqual(
    typeof styles.createZoomMediaMaxInlineSize,
    'function',
    'Expected zoom media size to be calculated by a testable helper',
  )
  assert.strictEqual(
    typeof styles.createZoomMediaCss,
    'function',
    'Expected zoom media CSS to be generated by a testable helper',
  )

  const source = styles.createZoomLayoutBodyStyleSource(
    {
      name: 'reflowable',
      width: 1000,
      height: 800,
      columnWidth: 460,
      gap: 40,
    },
    'horizontal',
  )

  assert.strictEqual(styles.createZoomMediaMaxInlineSize(source, 2), 210)
  assert.match(
    styles.createZoomMediaCss(source, 2),
    /max-inline-size:\s*210px !important/,
    'zoomed media must fit within the scaled single-page content column',
  )
}

function testZoomPinsExplicitDecorativeBackgroundsToViewport() {
  assert.strictEqual(
    typeof styles.createZoomDecorativeBackgroundStyles,
    'function',
    'Expected zoom background compensation to be testable',
  )

  assert.deepStrictEqual(
    styles.createZoomDecorativeBackgroundStyles(
      {
        backgroundImage: 'url("../Images/back.png")',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: '100% 100%',
        backgroundPositionX: '100%',
        backgroundPositionY: '100%',
        backgroundSize: '50% auto',
      },
      1.5,
    ),
    {
      backgroundAttachment: 'fixed',
    },
    'bottom decorative backgrounds should use the iframe viewport as their zoom anchor',
  )

  assert.deepStrictEqual(
    styles.createZoomDecorativeBackgroundStyles(
      {
        backgroundImage: 'url("../Images/header.png")',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: '0% 0%',
        backgroundPositionX: '0%',
        backgroundPositionY: '0%',
        backgroundSize: '40% auto',
      },
      1.5,
    ),
    {
      backgroundAttachment: 'fixed',
    },
    'top-left decorative backgrounds with explicit positioning should also use the viewport as their zoom anchor',
  )

  assert.deepStrictEqual(
    styles.createZoomDecorativeBackgroundStyles(
      {
        backgroundImage: 'url("../Images/side.png")',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: '100% 50%',
        backgroundPositionX: '100%',
        backgroundPositionY: '50%',
        backgroundSize: '12em auto',
      },
      1.5,
    ),
    {
      backgroundAttachment: 'fixed',
    },
    'right-center decorative backgrounds with explicit positioning should also use the viewport as their zoom anchor',
  )
}

function testZoomLeavesNonDecorativeBackgroundsAlone() {
  assert.deepStrictEqual(
    styles.createZoomDecorativeBackgroundStyles(
      {
        backgroundImage: 'url("../Images/paper.png")',
        backgroundRepeat: 'repeat-y',
        backgroundPosition: '0% 0%',
        backgroundPositionX: '0%',
        backgroundPositionY: '0%',
        backgroundSize: 'contain',
      },
      1.5,
    ),
    {},
    'repeated or fitted page backgrounds must keep authored sizing',
  )

  assert.deepStrictEqual(
    styles.createZoomDecorativeBackgroundStyles(
      {
        backgroundImage: 'url("../Images/header.png")',
        backgroundRepeat: 'no-repeat',
        backgroundPosition: '50% 0%',
        backgroundPositionX: '50%',
        backgroundPositionY: '0%',
        backgroundSize: 'contain',
      },
      1.5,
    ),
    {},
    'fitted page backgrounds must keep authored sizing',
  )
}

for (const run of [
  testZoomBodyStylesSkipNonNumericValues,
  testZoomBodyStylesCanUseCurrentLayout,
  testZoomBodyStylesUseVerticalPhysicalAxes,
  testZoomBodyStylesUseSinglePageVerticalStride,
  testZoomMediaUsesScaledContentColumnWidth,
  testZoomPinsExplicitDecorativeBackgroundsToViewport,
  testZoomLeavesNonDecorativeBackgroundsAlone,
]) {
  test(run.name, run)
}
